### ISSUE TITLE
v3.1.1 hard freezes

### ISSUE THREAD

**Issue by troyBORG** [bontebok/ResoniteIPv6Mod#4]
When I run v3.1.1 on my headless.  When I try to join it on my desktop I just hard freeze.  But if I put 3.1.0 on the headless I connect no issues.

Desktop Log
[DESKTOP-H0FLKOJ - 2024.7.15.1359 - 2024-07-16 00_13_27.log](https://github.com/user-attachments/files/16243464/DESKTOP-H0FLKOJ.-.2024.7.15.1359.-.2024-07-16.00_13_27.log)

Headless Log:
[2024.7.15.1359-2024-07-16-00_07_08.log](https://github.com/user-attachments/files/16243483/2024.7.15.1359-2024-07-16-00_07_08.log)

**Comment by bontebok** [comment]
This should be resolved, can you test and let me know if there are any further issues? Thanks!
